# Generated by Django 5.2.1 on 2025-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs', '0003_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='souvenirs.category'),
        ),
    ]
