# Generated by Django 5.2.1 on 2025-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs', '0006_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_url',
            field=models.URLField(blank=True, help_text='External link to purchase this product', null=True),
        ),
    ]
