# Generated by Django 5.2.1 on 2025-09-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs', '0012_alter_product_original_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('e-Sewa', 'e-Sewa'), ('cash', 'Cash')], max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_completed', models.BooleanField(default=False)),
                ('Order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='souvenirs.order')),
            ],
        ),
    ]
