# Generated by Django 5.2.1 on 2025-09-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs', '0013_remove_order_payment_method_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
